"""PySpark process mining utilities for large event logs."""

__version__ = "0.1.0"

from .bottleneck import duration as bottleneck_duration
from .dimensions import tracking as dimensions_tracking
from .eventlog import preparation as eventlog_preparation
from .kpis import metrics as kpis_metrics
from .variants import analysis as variants_analysis

from .bottleneck.duration import (
    activity_loop_detection,
    activity_transition_matrix,
    longest_waiting_step_per_case,
    parallel_activity_flag,
    time_between_activity_occurrences,
    time_to_first_occurrence_from_case_start,
    transition_time_matrix,
    waiting_time_between_activities,
)
from .dimensions.tracking import (
    dimension_stability_flag,
    dimension_value_transition_matrix,
    distinct_nonnull_count_per_case,
    first_nonnull_value,
    last_nonnull_value,
    most_frequent_value_per_case,
    multi_value_case_rate,
    nonnull_entry_count_per_case,
    null_coverage_rate,
    number_of_value_changes,
    value_at_activity,
)
from .eventlog.preparation import (
    activity_occurrence_index,
    activity_position_ratio,
    activity_sequence_number,
    carry_forward_dimension_value,
    case_end_timestamp,
    case_start_timestamp,
    case_throughput_time,
    detect_concurrency,
    duplicate_activity_flag,
    event_count_per_case,
    first_nonnull_in_dimension,
    first_occurrence_of_activity,
    is_first_activity_flag,
    is_last_activity_flag,
    last_nonnull_in_dimension,
    last_occurrence_of_activity,
    make_chronological_window,
    missing_activity_flag,
    next_activity,
    previous_activity,
    remaining_case_time,
    time_since_case_start,
    time_since_previous_event,
)
from .kpis.metrics import (
    activity_frequency_distribution,
    case_volume_over_time,
    rework_rate,
    stp_rate,
    throughput_time,
    throughput_time_percentiles,
)
from .variants.analysis import (
    case_variant_fingerprint,
    detect_variant_loops,
    filter_top_n_variants,
    flag_rare_variants,
    variant_attribute_profile,
    variant_coverage_ratio,
    variant_drift_over_time,
    variant_frequency_ranking,
)

__all__ = [
    "__version__",
    "activity_frequency_distribution",
    "activity_loop_detection",
    "activity_occurrence_index",
    "activity_position_ratio",
    "activity_sequence_number",
    "activity_transition_matrix",
    "bottleneck_duration",
    "carry_forward_dimension_value",
    "case_end_timestamp",
    "case_start_timestamp",
    "case_throughput_time",
    "case_variant_fingerprint",
    "case_volume_over_time",
    "detect_concurrency",
    "detect_variant_loops",
    "dimension_stability_flag",
    "dimension_value_transition_matrix",
    "dimensions_tracking",
    "distinct_nonnull_count_per_case",
    "duplicate_activity_flag",
    "event_count_per_case",
    "eventlog_preparation",
    "filter_top_n_variants",
    "first_nonnull_in_dimension",
    "first_nonnull_value",
    "first_occurrence_of_activity",
    "flag_rare_variants",
    "is_first_activity_flag",
    "is_last_activity_flag",
    "kpis_metrics",
    "last_nonnull_in_dimension",
    "last_nonnull_value",
    "last_occurrence_of_activity",
    "longest_waiting_step_per_case",
    "make_chronological_window",
    "missing_activity_flag",
    "most_frequent_value_per_case",
    "multi_value_case_rate",
    "next_activity",
    "nonnull_entry_count_per_case",
    "null_coverage_rate",
    "number_of_value_changes",
    "parallel_activity_flag",
    "previous_activity",
    "remaining_case_time",
    "rework_rate",
    "stp_rate",
    "time_between_activity_occurrences",
    "time_since_case_start",
    "time_since_previous_event",
    "time_to_first_occurrence_from_case_start",
    "throughput_time",
    "throughput_time_percentiles",
    "transition_time_matrix",
    "value_at_activity",
    "variant_attribute_profile",
    "variant_coverage_ratio",
    "variant_drift_over_time",
    "variant_frequency_ranking",
    "variants_analysis",
    "waiting_time_between_activities",
]
